---
title: "Intro to Middle Neighborhoods"
author: "Justin Elszasz, Mayor's Office of Innovation"
email: "justin.elszasz@baltimorecity.gov"
date: "Sunday, February 22, 2019"
css: iteam_pres.css
output: 
  slidy_presentation:
    toc: true
---

```{r setup, include = FALSE, echo = FALSE, message = FALSE, cache = TRUE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, include = T,
                      fig.width = 10, fig.height = 5)

``` 

```{r init, include = T}
source("../src/00_initialize.R")

library(leaflet)
library(knitr)
```

```{r get.data, cache = T}
hmt <- load_block_group_data(load.cache = T)
hoods <- get_neighborhood_boundaries()
```

```{r include = F}
# HUD area median income for Baltimore-Columbia-Towson
ami.2016 <- 86700
#ami.2018 <- 94900
```


# Housing Market Typology 

- Performed every few years by Reinvestment Fund
- 


# The Housing Market Typologies

# Our Middle Neighborhoods

Breaking "middle" into "lower middle" (F, G, H) and "upper middle" (D, E) and including "healthy" and "distressed:

```{r echo = F}
#mid.hoods.hmt <- subset(hmt, hmt.tier %in% c("lower middle", "upper middle"))

hmt.pal <- colorFactor(
  domain = hmt$hmt.tier,
  palette = c("gray65",
              "gray85",
              "#f0c650", 
              NA,
              iteam.colors[1])
)

leaflet() %>% 
  setView(lng = -76.6, lat = 39.3, zoom = 11) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(data = hmt, 
              color = iteam.colors[2],
              weight = 1,
              fillColor = ~hmt.pal(hmt.tier),
              #fillColor = iteam.colors[1],
              fillOpacity = .6,
              opacity = .7,
              label = ~as.character(hmt$MVA17HrdCd)
              ) %>%
  #addGeoJSON(hoods, weight = 1, color = "black", fillOpacity = 0)
  addPolygons(data = hoods, 
              weight = 2, 
              color = "black",
              opacity = 0.5,
              fillOpacity = 0, 
              label = ~hoods$label)
```

# Income levels in our middle neighborhoods are well below area's


```{r echo = F}
hmt@data %>% 
  filter(!is.na(Median_Household_Income.2016),
         Median_Household_Income.2016 > 0,
         hmt.tier %in% c("lower middle", "upper middle")) %>% 
  ggplot(aes(Median_Household_Income.2016)) +
  geom_freqpoly(aes(color = hmt.tier), bins = 50) +
  theme_iteam_presentations() +
  labs(
    title = paste0("Middle Neighborhood\nBlock Group Median Household Income\n",
                   "Distribution by HMT Market tier"),
    subtitle = "",
    x = "Median Household Income",
    y = "Count",
    caption = paste0("tier based on 2017 HMT analysis; ",
                     "median household incomes from 2012-2016 ACS data.")
  ) +
  geom_vline(aes(xintercept = ami.2016), color = iteam.colors[2]) +
  annotate("text", x = ami.2016 - 2500, y = 12,
           label = paste0("Baltimore-Columbia-Towson 2016 AMI:\n", dollar(ami.2016)),
           hjust = 1) +
  theme(plot.caption = element_text(hjust = 1, face = "plain"),
        legend.title = element_blank())
```

# Middle neighborhoods have more older homeowners


```{r echo = F}
hmt@data %>%
  filter(hmt.tier != "other") %>%
  group_by(hmt.tier) %>%
  summarise(mean.pct.ho.over65 = percent(mean(Percent_Homeowner_Over_65.2016)),
            med.pct.ho.over65 = percent(median(Percent_Homeowner_Over_65.2016))) %>%
  rename("Mean % Homeowners 65+" = mean.pct.ho.over65,
         "Median % Homeowners 65+" = med.pct.ho.over65) %>%
  kable()
```

```{r echo = F}
hmt@data %>% 
  filter(hmt.tier != "other") %>% 
  ggplot(aes(Percent_Homeowner_Over_65.2016)) +
  geom_freqpoly(aes(color = hmt.tier), stat = "density") +
  theme_iteam_presentations() +
  labs(
    title = "% Homeowners 65+ by HMT Market tier",
    subtitle = "",
    x = "% Homeowners 65+ y.o.",
    y = "Density",
    caption = paste0("tier based on 2017 HMT analysis; ",
                     "% homeowners 65 and over from 2012-2016 ACS data.")
  ) +
  theme(plot.caption = element_text(hjust = 1, face = "plain")) +
  scale_x_continuous(labels = percent)
```
```



