---
title: ""
author: "Justin Elszasz, Mayor's Office of Innovation"
email: "justin.elszasz@baltimorecity.gov"
date: "Tuesday, February 12, 2019"
output:
  html_notebook:
    code_folding: hide
    fig_height: 5
    fig_width: 10
    toc: yes
    toc_depth: 2
---

```{r setup, include = FALSE, echo = FALSE, message = FALSE, cache = TRUE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = F, 
                      message = F, 
                      include = T,
                      fig.width = 10,
                      fig.height = 5)
``` 



```{r}
source("../src/00_initialize.R")
library(RSocrata)
library(scales)
library(lubridate)
library(leaflet)
```


```{r}
hmt <- load_block_group_data(load.cache = T)
hoods <- get_neighborhood_boundaries()
cfs.narc <- read.socrata("https://data.baltimorecity.gov/resource/m8g9-abgb.json?description=NARCOTICSOutside")
#crime <- read.socrata("https://data.baltimorecity.gov/resource/4ih5-d5d5.json")
```

```{r}
cfs.narc <- cfs.narc %>% 
  unlist_lat_long("location.coordinates")

cfs.narc.geo <- cfs.narc %>% filter(!is.na(long))
  
cfs.narc.geo <- SpatialPointsDataFrame(
  cfs.narc.geo %>% select(long, lat), cfs.narc.geo,
  proj4string = CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

cfs.narc.geo <- spTransform(cfs.narc.geo, CRSobj = CRS("+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
```


```{r}
cfs.narc %>% glimpse
```

```{r}
cfs.narc %>% 
  count(!is.na(long)) %>% 
  mutate(pct = percent(n / sum(n))) 
```
```{r}
cfs.narc %>%
  mutate(call.ym = floor_date(calldatetime, "month")) %>%
  filter(call.ym < "2019-01-01") %>%
  count(call.ym) %>%
  ggplot(aes(call.ym, n)) +
  geom_line() +
  theme_iteam_google_docs()
```

```{r}
cfs.narc %>%
  count(year(calldatetime))
```




```{r}
set.seed(1)

map.points <- cfs.narc.geo[sample(1:length(cfs.narc.geo), 50000), ]

leaflet() %>%
  setView(lng = -76.6, lat = 39.3, zoom = 11) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(data = hmt,
              fillOpacity = 0,
              color = iteam.colors[2],
              opacity = 0.7,
              weight = 1) %>%
  addCircleMarkers(data = map.points, radius = 1, color = iteam.colors[5])

```

```{r}
cfs.narc.hmt <- over(cfs.narc.geo, hmt)

cfs.narc.geo@data <- bind_cols(cfs.narc.geo@data, cfs.narc.hmt)

cfs.narc.geo@data %>% head
```

```{r}
map.points <- cfs.narc.geo[sample(1:length(cfs.narc.geo), 10000), ]


pal <- colorFactor(
  domain = map.points$MVA17HrdCd,
  palette = topo.colors(15)
)


leaflet() %>%
  setView(lng = -76.6, lat = 39.3, zoom = 11) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(data = hmt,
              fillOpacity = 0,
              color = iteam.colors[2],
              opacity = 0.7,
              weight = 1) %>%
  addCircleMarkers(data = map.points, radius = 1, color = ~pal(map.points$MVA17HrdCd))

```

```{r}
tier.pop <- hmt@data %>% group_by(hmt.tier) %>% summarise(tier.pop = sum(Population.2016))

cfs.narc.geo@data %>%
  mutate(call.year = year(calldatetime)) %>%
  filter(call.year != 2019, !is.na(hmt.tier)) %>%
  count(hmt.tier) %>%
  left_join(tier.pop, by = "hmt.tier") %>%
  ungroup() %>% 
  mutate(annual.narc.call.per1000 = round(1000 * n / tier.pop / 4, 1),
         pct.pop = percent(tier.pop / sum(tier.pop, na.rm = T)),
         pct.calls = percent(n / sum(n))) %>%
  arrange(desc(annual.narc.call.per1000))
```

```{r}
cfs.narc.ratios.by.year <- cfs.narc.geo@data %>%
  mutate(call.year = year(calldatetime)) %>%
  filter(call.year != 2019,
         !is.na(hmt.tier)) %>%
  count(hmt.tier, call.year) %>%
  left_join(tier.pop, by = "hmt.tier") %>%
  mutate(narc.call.ratio = round(1000 *n / tier.pop, 1)) %>%
  ungroup() %>%
  group_by(call.year) %>%
  arrange(hmt.tier) %>%
  ungroup() %>%
  group_by(hmt.tier) %>%
  mutate(narc.call.ratio.pct.chg = narc.call.ratio / first(narc.call.ratio) - 1)

cfs.narc.ratios.by.year
```


```{r fig.width = 7, fig.height = 4}
cfs.narc.ratios.by.year %>%
  filter(hmt.tier != "other") %>%
  ggplot(aes(call.year, narc.call.ratio.pct.chg, color = hmt.tier)) +
  geom_line(size = 0.75) +
  theme_iteam_google_docs() +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = scales::percent, limits = c(-.5, .5)) +
  labs(title = "Changes in Narcotics 911 CFS by Housing Typology Tier\n2015 Base Year",
       y = "% Change in Narcotics Calls Ratio from 2015") 
  
```

```{r echo = F}
cfs.narc.bg <- over(cfs.narc.geo, hmt)

cfs.narc.geo@data <- bind_cols(cfs.narc.geo@data, cfs.narc.bg)

cfs.narc.bg.counts <- as.data.frame(table(year(cfs.narc.geo$calldatetime), cfs.narc.geo$bg)) %>% 
  spread(key = Var1, value = Freq) %>%
  rename(cfs.narc.2015 = "2015",
         cfs.narc.2016 = "2016",
         cfs.narc.2017 = "2017",
         cfs.narc.2018 = "2018",
         cfs.narc.2019 = "2019",
         bg = "Var2") %>%
  select(-cfs.narc.2019) %>%
  mutate(cfs.narc.4yr = cfs.narc.2015 + cfs.narc.2016 + cfs.narc.2017 + cfs.narc.2018)

hmt@data <- left_join(hmt@data, cfs.narc.bg.counts, by = "bg")
  
hmt@data <- hmt@data %>% 
  mutate(cfs.narc.ratio = 1000 * cfs.narc.4yr / Population.2016 / 4, # 4 years
         cfs.narc.ratio.2015 = 1000 * cfs.narc.2015 / Population.2016,
         cfs.narc.ratio.2016 = 1000 * cfs.narc.2016 / Population.2016,
         cfs.narc.ratio.2017 = 1000 * cfs.narc.2017 / Population.2016,
         cfs.narc.ratio.2018 = 1000 * cfs.narc.2018 / Population.2016,
         cfs.narc.ratio.pct.chg.15_18 = (cfs.narc.ratio.2018 - cfs.narc.ratio.2015) / cfs.narc.ratio.2015)

hmt@data %>% select(bg, cfs.narc.ratio, cfs.narc.ratio.2015) %>% head
```

```{r}
hmt@data %>%
  ggplot(aes(cfs.narc.ratio)) +
  geom_histogram() +
  theme_iteam_google_docs() +
  xlim(c(-50, 300))
```


```{r echo = F}
bins <- c(seq(0, 250, 20), Inf)
pal <- colorBin("YlOrRd", domain = hmt$cfs.narc.ratio, bins = bins)

leaflet() %>%
  setView(lng = -76.6, lat = 39.3, zoom = 11) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>% 
  addPolygons(data = hmt, 
              fillColor = ~pal(hmt$cfs.narc.ratio), 
              color = iteam.colors[2], 
              weight = 1, 
              fillOpacity = .6,
              label = ~as.character(round(hmt$cfs.narc.ratio, 2))) %>%
  addPolygons(data = hoods, 
              weight = 2, 
              color = "black",
              opacity = 0.5,
              fillOpacity = 0, 
              label = ~hoods$label)

```

# 2015 Narcotics CFS per 1,000 Residents

```{r echo = F}
leaflet() %>%
  setView(lng = -76.6, lat = 39.3, zoom = 11) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>% 
  addPolygons(data = hmt, 
              fillColor = ~pal(hmt$cfs.narc.ratio.2015), 
              color = iteam.colors[2], 
              weight = 1, 
              fillOpacity = .6,
              label = ~as.character(round(hmt$cfs.narc.ratio.2015, 2))) %>%
  addPolygons(data = hoods, 
              weight = 2, 
              color = "black",
              opacity = 0.5,
              fillOpacity = 0, 
              label = ~hoods$label)

```

# 2018 Narcotics CFS per 1,000 Residents

```{r echo = F}
leaflet() %>%
  setView(lng = -76.6, lat = 39.3, zoom = 11) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>% 
  addPolygons(data = hmt, 
              fillColor = ~pal(hmt$cfs.narc.ratio.2018), 
              color = iteam.colors[2], 
              weight = 1, 
              fillOpacity = .6,
              label = ~as.character(round(hmt$cfs.narc.ratio.2018, 2))) %>%
  addPolygons(data = hoods, 
              weight = 2, 
              color = "black",
              opacity = 0.5,
              fillOpacity = 0, 
              label = ~hoods$label)

```

```{r}
hmt@data %>% ggplot(aes(cfs.narc.ratio.pct.chg.15_18)) + geom_histogram() + xlim(c(-3,10))
```



```{r echo = F}
mid.big.change <- subset(hmt, 
                         hmt.tier %in% c("lower middle", "upper middle"))

bins <- c(-Inf, seq(-2, 2, .2), Inf)
pal <- colorBin("RdBu", domain = mid.big.change$cfs.narc.ratio.pct.chg.15_18, bins = bins, reverse = T)



leaflet() %>%
  setView(lng = -76.6, lat = 39.3, zoom = 11) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>% 
  addPolygons(data = mid.big.change, 
              fillColor = ~pal(mid.big.change$cfs.narc.ratio.pct.chg.15_18), 
              color = iteam.colors[2], 
              weight = 1, 
              fillOpacity = .6,
              label = ~as.character(round(mid.big.change$cfs.narc.ratio.pct.chg.15_18, 2))) %>%
  addPolygons(data = hoods, 
              weight = 2, 
              color = "black",
              opacity = 0.5,
              fillOpacity = 0, 
              label = ~hoods$label) 

```

```{r}
mid.big.change@data %>% 
  ggplot(aes(cfs.narc.ratio.pct.chg.15_18)) + 
  geom_histogram(bins = 7 0) +
  theme_iteam_presentations() +
  xlim(c(-1, 10))
```

