---
title: "Recent Sales Outliers"
author: "Justin Elszasz, Mayor's Office of Innovation"
email: "justin.elszasz@baltimorecity.gov"
date: "Thursday, February 28, 2019"
output:
  html_notebook:
    code_folding: hide
    fig_height: 5
    fig_width: 10
    toc: yes
    toc_depth: 2
---

```{r setup, include = FALSE, echo = FALSE, message = FALSE, cache = TRUE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F, include = T,
                      fig.width = 10, fig.height = 5, 
                      out.width = "100%", out.height = "100%")
options(scipen = 999)
```


```{r}
source("../src/00_initialize.R")


library(readxl)
library(RSocrata)
library(sp)
library(leaflet)
library(RODBC)
library(htmltools)


#sales <- load_sales_data(load.cache = T)
#real.prop.url <- "https://data.baltimorecity.gov/resource/6act-qzuy.json"
#real.prop <- read.socrata(real.prop.url, app_token = VARS$SOCRATA_TOKEN)
real.prop <- readRDS("../data/processed/real_prop.Rds")
#hoods <- get_neighborhood_boundaries()
hoods <- readRDS("../data/processed/hoods.Rds")
hmt <- load_block_group_data(load.cache = T)
hmt.hood <- read_excel("../data/raw/hmt/HMT by Neighborhood 2017.xlsx")

sales <- read_csv("../data/raw/sales/Sales from 2015.csv")
```

```{r}
# join HMT hood labels to hood boundaries

hoods@data <- hoods@data %>% left_join(hmt.hood, by = c("label" = "Neighborhood"))
```

First need to join up the real property data ([Open Baltimore]([http://data.baltimorecity.gov/Financial/Real-Property-Taxes/27w9-urtvto)) the sales data (provided by Steve, and with **deed dates from January 1, 2010 through October 2018**) so we have a neighborhood for as many sales as we can.

```{r}

sales <- sales %>% 
  separate(BlockLot, 
           sep = "(?<=[[:space:]]|[A-Z]\\B)", 
           into = c("sales.block", "sales.lot"),
           remove = F)


real.prop <- real.prop %>% rename(real.block = block, real.lot = lot)
```

```{r}
real.prop <- real.prop %>%
  mutate(real.block.clean = str_trim(gsub("^0+", "", real.block)),
         real.lot.clean = str_trim(gsub("^0+", "", real.lot)))

sales <- sales %>%
  mutate(sales.block.clean = str_trim(gsub("^0+", "", sales.block)),
         sales.lot.clean = str_trim(gsub("^0+", "", sales.lot)))
```

```{r}
sales <- sales %>%
  left_join(real.prop, 
            by = c("sales.block.clean" = "real.block.clean",
                   "sales.lot.clean" = "real.lot.clean")
            )

# sales <- sales %>% 
#   separate(location.coordinates, 
#            into = c("long", "lat"), 
#            sep = c(","), convert = T) %>%
#   mutate(long = as.numeric(gsub("c\\(", "", long)),
#          lat = as.numeric(gsub("\\)", "", lat)))

```




```{r}
sales <- sales %>% mutate_at(vars(saleDate), funs(ymd))
```



```{r}
library(htmltools)

hoods.labels <- paste0(
  hoods$label,
  "<br>2017 Housing Market Typology: ", hoods$`Predominant Code Ignoring Non-Residential`,
  "<br>Median Sales, 2015-2017: ", as.character(hoods$hood.median)
  
)



```



```{r}
mid.hoods <- hmt.hood %>% filter(`Predominant Code Ignoring Non-Residential` %in% c("D", "E", "F", "G", "H"))

```


```{r out.width="100%", width = 8}

mid.hoods.geo <- subset(hoods, 
                        tolower(label) %in% tolower(mid.hoods$Neighborhood))



mid.hoods.labels <- paste0(
  mid.hoods.geo$label,
  "<br>2017 Housing Market Typology: ", mid.hoods.geo$`Predominant Code Ignoring Non-Residential`,
  "<br>Median Sales, 2015-2017: ", as.character(mid.hoods.geo$hood.median)
  
)

```




# 3 Most Expensive in Each Neighborhood



```{r}
sales.mid.hoods.top3 <- sales %>%
  filter(year(saleDate) >= 2018,
         
         !grepl("NOT", rescode),
         neighborhood %in% mid.hoods$Neighborhood) %>%
  group_by(neighborhood) %>%
  arrange(desc(AdjustedSalesPrice)) %>%
  mutate(price.order = row_number()) %>%
  ungroup() %>%
  filter(price.order <= 3) %>%
  arrange(neighborhood, price.order)


sales.mid.hoods.top3.geo <- sales.mid.hoods.top3 %>%
  filter(!is.na(Longitude))
  
sales.mid.hoods.top3.geo <- SpatialPointsDataFrame(
  sales.mid.hoods.top3.geo %>% select(Longitude, Latitude), 
  sales.mid.hoods.top3.geo,
  proj4string = CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

sales.mid.hoods.top3.geo <- 
  spTransform(
    sales.mid.hoods.top3.geo, 
    CRSobj = CRS("+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")
    )
```

```{r}

sale.labels <- paste0(
  
   sales.mid.hoods.top3.geo$Address
  # sales.mid.hoods.top3.geo$`Street Name`, " ",
  # sales.mid.hoods.top3.geo$Suffix, 
  # "<br>Sale Price in 2018: ", 
  # as.character(sales.mid.hoods.top3.geo$`Sales Price`),
  # "<br>New Owner: ", sales.mid.hoods.top3.geo$new.owner
  #"<br>Permits Issued from 2017-2018: ", sales.mid.hoods.top3.geo$permit.count,
  #"<br>Total Permit Value from 2017-2018: ", sales.mid.hoods.top3.geo$permit.total.value
)


leaflet() %>%
  setView(lng = -76.6, lat = 39.3, zoom = 11) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>% 
  addPolygons(data = hoods, 
              weight = 2, 
              
              color = "black",
              opacity = 0.5,
              fillOpacity = 0, 
              label = ~lapply(hoods.labels, HTML)) %>%
  addPolygons(data = mid.hoods.geo, 
              weight = 2, 
              #color = "black",
              opacity = 0.0,
              fillOpacity = .2,
              fillColor = iteam.colors[3],
              label = ~lapply(mid.hoods.labels, HTML)) %>%
  addCircleMarkers(data = sales.mid.hoods.top3.geo, 
                   color = iteam.colors[1],
                   opacity = 1,
                   radius = 2,
                   label = ~lapply(sale.labels, HTML))
```





```{r}
library(plotly)
plot_hood_sales_timeline <- function(hood){
  
  df <- sales %>% 
    filter(neighborhood == hood, 
           !grepl("NOT", rescode))
  
  g <- df %>%
    ggplot(aes(saleDate, AdjustedSalesPrice)) +
    geom_point(
      color = ifelse(df$propertyaddress %in% sales.mid.hoods.top3$propertyaddress, 
                     "red", "black"),
      aes(text = df$propertyaddress)) +
    theme_iteam_google_docs() +
    ylim(c(0, 500000)) +
    geom_smooth() +
    ggtitle(hood)
  
  ggplotly(g)
}

```

```{r}
plot_hood_sales_timeline("Dorchester")
```






















